### ISSUE TITLE
set sourceMappingURL root

### ISSUE THREAD

**Issue by olanod** [gruntjs/grunt-contrib-coffee#117]
My coffee task looks like this:

```
coffee:
     dev:
       options:
         bare: yes
         sourceMap: yes
       expand: yes
       cwd: '<%= srcDir %>/js'
       dest: '<%= srcDir %>/js'
       src: '**/*.coffee'
       ext: '.js'
```

For a js file in my `src/js` directory, for example `app.js`, it gets compiled with the following sourceMappingURL: `//# sourceMappingURL=../../src/js/app.js.map` but it should be  `//# sourceMappingURL=app.js.map`. Is there a way to specify this Url's root?
