### ISSUE TITLE
Is it possible to keep the same source folder structure in the destination folder?

### ISSUE THREAD

**Issue by ivanvolti** [gruntjs/grunt-contrib-coffee#18]
Source:

```
src/app
│
├── app.coffee
├── router.coffee
├── utils
│   ├── csrf.coffee
│   └── tastypie.coffee
└── views
    ├── alert_view.coffee
    ├── dialog_view.coffee
    ├── editable_view.coffee
    ├── libraries_view.coffee
    ├── library_view.coffee
    ├── navigation_view.coffee
    └── profile_view.coffee
```

Destination (the same dirs structure):

```
dest/app
│
├── app.js
├── router.js
├── utils
│   ├── csrf.js
│   └── tastypie.js
└── views
    ├── alert_view.js
    ├── dialog_view.js
    ├── editable_view.js
    ├── libraries_view.js
    ├── library_view.js
    ├── navigation_view.js
    └── profile_view.js
```

To make it possible before I had this in my Grunt 0.3.x config file:

```
coffee:
  compile:
    files:
      'dest/app/*.js': 'src/app/**/*.coffee'

    options:
      basePath: 'src/app'
```

The question is how I can get the same result using the new grunt-contrib-coffee (0.4.x) version?
